#!/bin/bash

COUNT=0
CURRENT_DIR="$PWD"
PD="device/samsung/kyleprods/patches"
PATCHES=(
'frameworks/base		frameworks_base.patch'
'frameworks/native		frameworks_native.patch'
'packages/services/Telephony	packages_services_Telephony.patch'
'system/core			system_core.patch'
)

while [ "x${PATCHES[COUNT]}" != "x" ]
do
	CURRENT="${PATCHES[COUNT]}"
	FOLDER=`echo "$CURRENT" | awk '{print $1}'`
	PATCH=`echo "$CURRENT" | awk '{print $2}'`

	cd "$FOLDER"
	echo Patching "$FOLDER" ...
	git apply "$CURRENT_DIR/$PD/$PATCH"
	cd "$CURRENT_DIR"

	COUNT=$(($COUNT + 1))
done
